# `KNN Estimator from Scratch`
------------

## Load iris csv file into dataframe

In [5]:
import pandas as pd
df = pd.read_csv("C:\\Users\\ramreddymyla\\Google Drive\\01 DS ML DL NLP and AI With Python Lab Copy\\02 Lab Data\\Python\\iris.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal_length    150 non-null float64
sepal_width     150 non-null float64
petal_length    150 non-null float64
petal_width     150 non-null float64
species         150 non-null object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [6]:
df.loc[[0,50,100]]

sepal_length  sepal_width  petal_length  petal_width     species
0             5.1          3.5           1.4          0.2      setosa
50            7.0          3.2           4.7          1.4  versicolor
100           6.3          3.3           6.0          2.5   virginica

In [8]:
# convert df into 2d numpy array
df_np=df.values
len(df_np)

150

In [11]:
df_np[1]

array([4.9, 3.0, 1.4, 0.2, 'setosa'], dtype=object)

## Collect data without y/target values

In [34]:
unknown_samples=[[5.1, 3.5, 1.4, 0.2],
                 [7.0, 3.2, 4.7, 1.4],
                 [6.3, 3.3, 6.0, 2.5]]

## Write code to Calculate Euclidean distance

In [1]:
# Calculate Euclidean distance
import numpy as np
def ed(known_sample,unknown_samples):
    distance =0
    for i in range(len(known_sample)-1): # to exclude y column we are subtracting -1
        distance+=(known_sample[i]-unknown_samples[i]) **2
    return np.sqrt(distance)

### Test with `two features` data

In [2]:
ed([-1,1,"apple"],[3,4])

5.0

### Test with `four features` iris data

In [3]:
ed(known_sample=[5.1, 3.5, 1.4, 0.2],
   unknown_samples=[5.1, 3.5, 1.4, 0.2])

0.0

## Write code to Locate the most `similar neighbors`

In [26]:
# Locate the most similar neighbors
def get_neighbors(known_sample, unknown_samples, n_neighbors):
    distances = [] # empty list
    for ks in known_sample:
        dist = ed(ks, unknown_samples)
        ##print(ks)
        #print(unknown_samples)
        #print(dist)        
        distances.append((ks, dist))
    #print(distances)
    distances.sort(key=lambda tup: tup[1])
    neighbors = [] # empty list
    for i in range(n_neighbors):
        neighbors.append(distances[i][0])
    return neighbors        

In [27]:
t=([5.1, 3.5, 1.4, 0.2, 'setosa'], 0.0)

In [28]:
t[1]

0.0

### Testing with `setosa` type of unknow sample

In [29]:
get_neighbors(known_sample=df_np,
              unknown_samples=[5.1, 3.5, 1.4, 0.2],
              n_neighbors=3)

[array([5.1, 3.5, 1.4, 0.2, 'setosa'], dtype=object),
 array([5.1, 3.5, 1.4, 0.3, 'setosa'], dtype=object),
 array([5.0, 3.6, 1.4, 0.2, 'setosa'], dtype=object)]

### Testing with `versicolor` type of unknow sample

In [30]:
get_neighbors(known_sample=df_np,
              unknown_samples=[7.0, 3.2, 4.7, 1.4],
              n_neighbors=3)

[array([7.0, 3.2, 4.7, 1.4, 'versicolor'], dtype=object),
 array([6.9, 3.1, 4.9, 1.5, 'versicolor'], dtype=object),
 array([6.7, 3.1, 4.7, 1.5, 'versicolor'], dtype=object)]

### Testing with `virginica` type of unknow sample

In [31]:
get_neighbors(known_sample=df_np,
              unknown_samples=[6.3, 3.3, 6.0, 2.5],
              n_neighbors=3)

[array([6.3, 3.3, 6.0, 2.5, 'virginica'], dtype=object),
 array([6.3, 3.4, 5.6, 2.4, 'virginica'], dtype=object),
 array([6.7, 3.3, 5.7, 2.5, 'virginica'], dtype=object)]

## Write code to Make a `classification prediction` with neighbors

In [32]:
# Make a classification prediction with neighbors
def predict_classification(known_sample, unknown_samples, n_neighbors):
    rs=[]
    for uks in unknown_samples:
        neighbors = get_neighbors(known_sample, uks, n_neighbors)
        output_values = [row[-1] for row in neighbors]
        prediction = max(set(output_values), key=output_values.count)
        rs.append(prediction)
    return rs

In [36]:
unknown_samples

[[5.1, 3.5, 1.4, 0.2], [7.0, 3.2, 4.7, 1.4], [6.3, 3.3, 6.0, 2.5]]

In [35]:
predict_classification(df_np,unknown_samples,4)

['setosa', 'versicolor', 'virginica']