# Exercise 1: Explore `Toy-Datasets`
- Scikit-learn comes with a few small standard datasets that do not require to download any file from some external website
    https://scikit-learn.org/stable/datasets/index.html#toy-datasets
- For more data sets refer https://archive.ics.uci.edu/ml/index.php

## Explore iris Dataset

In [4]:
from sklearn import datasets

In [2]:
iris = datasets.load_iris()         # 01. Load iris data set

In [3]:
print(type(iris))                   # 02. datatype of iris data set

<class 'sklearn.utils.Bunch'>


In [4]:
print(iris.keys())                  # 03. Keys of iris data set

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [7]:
print(iris.data)                 # 04. Observe iris data a.k.a fetures

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [8]:
print(iris.target)                  # 05. Observe iris target key

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [9]:
print(iris.target_names)            # 06. Observe iris target_names key

['setosa' 'versicolor' 'virginica']


In [10]:
print(iris.DESCR)                   # 07. Observe iris descr

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [11]:
print(iris.feature_names)           # 08. Observe iris feature_names

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [12]:
print(type(iris.data))              # 09. Datatype of iris data key
print(type(iris.target))            # 10. datatype of iris target key
print(type(iris.target_names))      # 11. datatype of iris target_names key
print(type(iris.DESCR))             # 12. datatype of iris descr key
print(type(iris.feature_names))     # 13. datatype of iris feature_names key


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'str'>
<class 'list'>


In [13]:
print(iris.data.shape)              # 14. Nmber of rows and columns

(150, 4)


## Similarly explore remaining toy datasets


In [9]:
# toy datasets
rs =[]
for i in dir(datasets):
    if i.startswith("load_"):
        rs.append(i)
print(f"the number of toy data sets in sklearn are : {len(rs)}") 
rs

the number of toy data sets in sklearn are : 12


['load_boston',
 'load_breast_cancer',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_linnerud',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine']

## Exercise 2: Create `DataFrame` from sklearn `Bunch`

In [ ]:
from sklearn import datasets
import pandas as pd
print(" ##### 01. Load iris data set ##### ")
iris = datasets.load_iris()
print(" ##### 02. Create Data Frame ##### ")
df = pd.DataFrame(iris.data, columns=iris.feature_names)
print(df.head(2))

 ##### 01. Load iris data set ##### 
 ##### 02. Create Data Frame ##### 
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2


## Exercise 3: Create a bunch with our own data (Just Knowledge  purpose ,not useful in live) 

In [2]:
import sklearn

In [5]:
dataset = sklearn.datasets.base.Bunch(data=[[80,6,10],
                                           [60,5.5,60]], 
                                      target=["Male","Female"],
                                     feature_names=["weight","Height","hair Length"],
                                     DESCR = ["my first data set"])

In [6]:
type(dataset)

sklearn.utils.Bunch

In [7]:


dataset.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR'])

In [8]:
dataset.data

[[80, 6, 10], [60, 5.5, 60]]

In [8]:
dataset.target

['Male', 'Female']

In [12]:
dataset.feature_names

['weight', 'Height', 'hair Length']