# Logistic Regression with Multi Labels(aka `multinomial`)
-----------------

## Step 1: Import Required Modules

In [1]:
import os
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix

C:\Users\ramreddymyla\Anaconda3\envs\dl\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\ramreddymyla\Anaconda3\envs\dl\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


## Step 2: Load `csv file` and Understand `X` and `y` Data

In [4]:
# Change Directory to location ,where we have csv file
os.chdir("C:\\Users\\ramreddymyla\\Google Drive\\01 DS ML DL NLP and AI With Python Lab Copy\\02 Lab Data\\Python")

In [5]:
# Load csv file into DataFrame
df = pd.read_csv("iris.csv")

In [6]:
# Get top 5 Rows
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [7]:
# Observe all the columns
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [8]:
# create a dataframe X with required input columns
X=df.loc[:,df.columns!="species"] 

In [9]:
type(X)

pandas.core.frame.DataFrame

In [10]:
X.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [11]:
y=df.species # create a series with target values

In [12]:
y.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [13]:
y.replace(['setosa', 'versicolor', 'virginica'],[0,1,2],inplace=True)

In [14]:
y.unique()

array([0, 1, 2], dtype=int64)

In [15]:
X=X.values # converting df to 2d Numpy Array

In [16]:
type(X)

numpy.ndarray

In [17]:
X.ndim

2

In [18]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [19]:
y=y.values # converting Series to 1d Numpy Array

In [20]:
type(y)

numpy.ndarray

In [21]:
y.ndim

1

In [22]:
y[:5]

array([0, 0, 0, 0, 0], dtype=int64)

## Step 3: Split Data for training and testing

In [23]:
seed=42

In [71]:
train_test_split?

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y,
                                                    test_size=0.3, # train : 105 # test : 45
                                                    random_state=seed, # reproduce # seed
                                                    stratify=y) # input data ratio(50:50:50) = train data ratio(35:35:35) = test data ratio(15:15:15)

In [26]:
# Count of each class in orginal data
unique, counts = np.unique(y, return_counts=True)
dict(zip(unique, counts))

{0: 50, 1: 50, 2: 50}

In [27]:
# Count of each class in train sample data
unique, counts = np.unique(y_train, return_counts=True)
dict(zip(unique, counts))

{0: 35, 1: 35, 2: 35}

In [28]:
# Count of each class in test sample data
unique, counts = np.unique(y_test, return_counts=True)
dict(zip(unique, counts))

{0: 15, 1: 15, 2: 15}

## Step 4: Fit The Model

In [30]:
logreg_clf = LogisticRegression(C=1e5, solver='lbfgs', multi_class='multinomial')

In [31]:
logreg_clf.fit(X_train, y_train)

C:\Users\ramreddymyla\Anaconda3\envs\dl\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


LogisticRegression(C=100000.0, class_weight=None, dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='multinomial', n_jobs=None,
                   penalty='l2', random_state=None, solver='lbfgs', tol=0.0001,
                   verbose=0, warm_start=False)

## Step 5: Predict labels of test data

In [32]:
y_test_pred = logreg_clf.predict(X_test)

In [34]:
print("Test set predictions:\n {}".format(y_test_pred))

Test set predictions:
 [2 1 1 1 2 2 1 1 0 2 0 0 2 2 0 2 1 0 0 0 1 0 1 2 1 1 1 1 1 0 1 2 1 0 2 0 0
 0 0 1 1 0 1 2 1]


In [36]:
y_test

array([2, 1, 2, 1, 2, 2, 1, 1, 0, 2, 0, 0, 2, 2, 0, 2, 1, 0, 0, 0, 1, 0,
       1, 2, 2, 1, 1, 1, 1, 0, 2, 2, 1, 0, 2, 0, 0, 0, 0, 1, 1, 0, 2, 2,
       1], dtype=int64)

In [35]:
np.bincount(y_test_pred)

array([15, 19, 11], dtype=int64)

## Step 6: Accuracy

In [37]:
accuracy_score(y_test,y_test_pred)

0.9111111111111111

> **or**

In [38]:
print(logreg_clf.score(X_test, y_test))

0.9111111111111111


## Step 7: Confusion Matrix

In [39]:
confusion_matrix(y_test,y_test_pred)

array([[15,  0,  0],
       [ 0, 15,  0],
       [ 0,  4, 11]], dtype=int64)