# `KNeighborsClassifier With sklearn`
-----------------


## High level End to End ML project
- Get data(Files,RDBMS,NO-SQL DATABASES,GRAPH Databases)
- Identify X(Independent Variables),y(Dependent Varaibale)
    * X (2D numpy array)
    * y (1D numpy array)
- Pre processing of data
    - (Missing values(ex : Female age not ready to reveal)
    - outliers(ex : age is 300)
    - normalization/Unit variance
    - features identification(dimensions reduction)
    - converting unbalanced data into balanced data
    - etc
- Split the data into Train and Test
- Fit / Train model using train data
- Predict on test data
- Metrics(Accuracy)
- If we are not happy with accuracy then do `hyper parameter tunning` and rebuild the model
- Save model
- Using This model Create Rest API
- Test Rest API Using Post man
- UI people use this API and design web application

## Import Required Modules

In [4]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

C:\Users\ramreddymyla\Anaconda3\envs\dl\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\ramreddymyla\Anaconda3\envs\dl\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\ramreddymyla\Anaconda3\envs\dl\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


## Load `csv file` and Understand `X` and `y` Data

In [5]:
# Change Directory to location ,where we have csv file
os.chdir("C:\\Users\\ramreddymyla\\Google Drive\\01 DS ML DL NLP and AI With Python Lab Copy\\02 Lab Data\\Python")

In [6]:
# Load csv file into DataFrame
df = pd.read_csv("iris.csv")

In [7]:
# Get top 5 Rows
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [8]:
# Observe all the columns
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [9]:
# create a dataframe X with required input columns
X=df.loc[:,df.columns!="species"] 

In [10]:
type(X)

pandas.core.frame.DataFrame

In [11]:
X.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [12]:
y=df.species # create a series with target values

In [13]:
y.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [14]:
y.replace(['setosa', 'versicolor', 'virginica'],[0,1,2],inplace=True)

In [15]:
y.unique()

array([0, 1, 2], dtype=int64)

In [16]:
X=X.values # converting df to 2d Numpy Array

In [17]:
type(X)

numpy.ndarray

In [18]:
X.ndim

2

In [19]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [20]:
y=y.values # converting Series to 1d Numpy Array

In [21]:
type(y)

numpy.ndarray

In [22]:
y.ndim

1

In [23]:
y[:5]

array([0, 0, 0, 0, 0], dtype=int64)

## Split Data for training and testing

In [24]:
seed=42

In [25]:
train_test_split?

Signature: train_test_split(*arrays, **options)
Docstring:
Split arrays or matrices into random train and test subsets

Quick utility that wraps input validation and
``next(ShuffleSplit().split(X, y))`` and application to input data
into a single call for splitting (and optionally subsampling) data in a
oneliner.

Read more in the :ref:`User Guide <cross_validation>`.

Parameters
----------
*arrays : sequence of indexables with same length / shape[0]
    Allowed inputs are lists, numpy arrays, scipy-sparse
    matrices or pandas dataframes.

test_size : float, int or None, optional (default=None)
    If float, should be between 0.0 and 1.0 and represent the proportion
    of the dataset to include in the test split. If int, represents the
    absolute number of test samples. If None, the value is set to the
    complement of the train size. If ``train_size`` is also None, it will
    be set to 0.25.

train_size : float, int, or None, (default=None)
    If float, should be between 0.0 a

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y,
                                                    test_size=0.3, # train : 105 # test : 45
                                                    random_state=seed, # reproduce # seed
                                                    stratify=y) # input data ratio(50:50:50) = train data ratio(35:35:35) = test data ratio(15:15:15)

1. Did you understand stratify ? 

    `Must Read:`https://en.wikipedia.org/wiki/Stratified_sampling
2. Did you understand random_state?
3. What is Balanced Data ?

In [27]:
# Count of each class in orginal data
unique, counts = np.unique(y, return_counts=True)
dict(zip(unique, counts))

{0: 50, 1: 50, 2: 50}

In [28]:
# Count of each class in train sample data
unique, counts = np.unique(y_train, return_counts=True)
dict(zip(unique, counts))

{0: 35, 1: 35, 2: 35}

In [29]:
# Count of each class in test sample data
unique, counts = np.unique(y_test, return_counts=True)
dict(zip(unique, counts))

{0: 15, 1: 15, 2: 15}

## Fit The Model

In [30]:
knn = KNeighborsClassifier(n_neighbors=8)

In [31]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=8, p=2,
                     weights='uniform')

## Predict labels of test data

In [32]:
# observe top 10 samples proba
knn.predict_proba(X_test)[:10]

array([[0.   , 0.   , 1.   ],
       [0.   , 0.875, 0.125],
       [0.   , 0.5  , 0.5  ],
       [0.   , 0.75 , 0.25 ],
       [0.   , 0.375, 0.625],
       [0.   , 0.   , 1.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 0.   , 1.   ]])

In [33]:
y_pred = knn.predict(X_test)

In [34]:
print(f"\nTest set predictions:\n\n {y_pred}")


Test set predictions:

 [2 1 1 1 2 2 1 1 0 2 0 0 2 2 0 2 1 0 0 0 1 0 1 2 1 1 1 1 1 0 2 2 1 0 2 0 0
 0 0 1 1 0 1 2 1]


In [35]:
y_test

array([2, 1, 2, 1, 2, 2, 1, 1, 0, 2, 0, 0, 2, 2, 0, 2, 1, 0, 0, 0, 1, 0,
       1, 2, 2, 1, 1, 1, 1, 0, 2, 2, 1, 0, 2, 0, 0, 0, 0, 1, 1, 0, 2, 2,
       1], dtype=int64)

In [36]:
#np.bincount?

In [37]:
np.bincount(y_pred)

array([15, 18, 12], dtype=int64)

## Accuracy

In [38]:
accuracy_score(y_test,y_pred)

0.9333333333333333

> **or**

In [39]:
print(knn.score(X_test, y_test))

0.9333333333333333


In [40]:
accuracy_score?

Signature: accuracy_score(y_true, y_pred, normalize=True, sample_weight=None)
Docstring:
Accuracy classification score.

In multilabel classification, this function computes subset accuracy:
the set of labels predicted for a sample must *exactly* match the
corresponding set of labels in y_true.

Read more in the :ref:`User Guide <accuracy_score>`.

Parameters
----------
y_true : 1d array-like, or label indicator array / sparse matrix
    Ground truth (correct) labels.

y_pred : 1d array-like, or label indicator array / sparse matrix
    Predicted labels, as returned by a classifier.

normalize : bool, optional (default=True)
    If ``False``, return the number of correctly classified samples.
    Otherwise, return the fraction of correctly classified samples.

sample_weight : array-like of shape = [n_samples], optional
    Sample weights.

Returns
-------
score : float
    If ``normalize == True``, return the fraction of correctly
    classified samples (float), else returns the number

> In above exercise, How you know `n_neighbors=8`? do you have any way to find `Best Parameter` ???

## Hyper Parameter Tuning 
1. Useing `our own code`
2. Useing `GridSearchCV`
3. Useing `RandomizedSearchCV`

### Method 1: Use your `own Code`

In [41]:
rs= []
for i in list(range(1,20)):
    knn = KNeighborsClassifier(n_neighbors=i)
    #print(knn)
    knn.fit(X, y)
    y_test_pred = knn.predict(X_test)
    rs.append((i,accuracy_score(y_test,y_test_pred)))    

In [42]:
rs[1]

(2, 0.9555555555555556)

#### change multiple args

In [43]:
scores = [] # empty list
for i in range(1,11):
    for w in ['uniform','distance']:
        for a in ['ball_tree', 'kd_tree', 'brute']:
            knn_clf_obj=KNeighborsClassifier(n_neighbors=i,
                                             weights=w,
                                            algorithm=a)
            knn_clf_obj.fit(X_train,y_train)
            y_test_pred=knn_clf_obj.predict(X_test)
            scores.append((i,w,a,accuracy_score(y_test,y_test_pred)))
scores    

[(1, 'uniform', 'ball_tree', 0.9333333333333333),
 (1, 'uniform', 'kd_tree', 0.9333333333333333),
 (1, 'uniform', 'brute', 0.9333333333333333),
 (1, 'distance', 'ball_tree', 0.9333333333333333),
 (1, 'distance', 'kd_tree', 0.9333333333333333),
 (1, 'distance', 'brute', 0.9333333333333333),
 (2, 'uniform', 'ball_tree', 0.9111111111111111),
 (2, 'uniform', 'kd_tree', 0.9111111111111111),
 (2, 'uniform', 'brute', 0.9111111111111111),
 (2, 'distance', 'ball_tree', 0.9333333333333333),
 (2, 'distance', 'kd_tree', 0.9333333333333333),
 (2, 'distance', 'brute', 0.9333333333333333),
 (3, 'uniform', 'ball_tree', 0.9555555555555556),
 (3, 'uniform', 'kd_tree', 0.9555555555555556),
 (3, 'uniform', 'brute', 0.9555555555555556),
 (3, 'distance', 'ball_tree', 0.9555555555555556),
 (3, 'distance', 'kd_tree', 0.9555555555555556),
 (3, 'distance', 'brute', 0.9555555555555556),
 (4, 'uniform', 'ball_tree', 0.9555555555555556),
 (4, 'uniform', 'kd_tree', 0.9555555555555556),
 (4, 'uniform', 'brute', 0.93

### Method 2: Use `GridSearchCV`

#### What is CV ??

[Refer help document of sklearn](https://scikit-learn.org/stable/modules/cross_validation.html)

In [44]:
from sklearn.model_selection import GridSearchCV

In [95]:
#GridSearchCV?

In [80]:
param_grid = {'n_neighbors': np.arange(2, 10),
              'weights': ['uniform','distance'],
              'algorithm':['ball_tree', 'kd_tree', 'brute']}

In [81]:
knn_cv = GridSearchCV(knn,param_grid)

In [82]:
knn_cv.fit(X, 
           y)

C:\Users\ramreddymyla\Anaconda3\envs\dl\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=19, p=2,
                                            weights='uniform'),
             iid='warn', n_jobs=None,
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': array([2, 3, 4, 5, 6, 7, 8, 9]),
                         'weights': ['uniform', 'distance']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [96]:
#knn_cv.cv_results_

In [87]:
knn_cv.best_estimator_

KNeighborsClassifier(algorithm='ball_tree', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [88]:
knn_cv.best_params_

{'algorithm': 'ball_tree', 'n_neighbors': 5, 'weights': 'uniform'}

In [89]:
knn_cv.best_score_

0.9866666666666667

In [90]:
knn_cv.best_index_

6

In [94]:
knn_cv.n_splits_

3

### Method 3: Use `RandomizedSearchCV`

In [97]:
from sklearn.model_selection import RandomizedSearchCV
#RandomizedSearchCV?

In [98]:
knn_cv_rand = RandomizedSearchCV(knn,param_grid,random_state=seed,cv=5)

In [99]:
knn_cv_rand.fit(X,y)

RandomizedSearchCV(cv=5, error_score='raise-deprecating',
                   estimator=KNeighborsClassifier(algorithm='auto',
                                                  leaf_size=30,
                                                  metric='minkowski',
                                                  metric_params=None,
                                                  n_jobs=None, n_neighbors=19,
                                                  p=2, weights='uniform'),
                   iid='warn', n_iter=10, n_jobs=None,
                   param_distributions={'algorithm': ['ball_tree', 'kd_tree',
                                                      'brute'],
                                        'n_neighbors': array([2, 3, 4, 5, 6, 7, 8, 9]),
                                        'weights': ['uniform', 'distance']},
                   pre_dispatch='2*n_jobs', random_state=42, refit=True,
                   return_train_score=False, scoring=None, verbose=0)

In [100]:
knn_cv_rand.best_params_

{'weights': 'distance', 'n_neighbors': 7, 'algorithm': 'kd_tree'}

In [101]:
knn_cv_rand.best_score_

0.98

## Save The model


In [56]:
import pickle
# save the model to disk
filename = 'knn_model.sav'
pickle.dump(knn, open(filename, 'wb'))

## Load The model

In [57]:
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X_test, y_test)
loaded_model
print(result)

0.9555555555555556


In [58]:
result1 = loaded_model.predict([[5.1,3.5,1.4,0.2]])
print(result1)
result2 = loaded_model.predict([[4.9,2.4,3.3,1]]) 
print(result2)
result3 = loaded_model.predict([[7.7,3.8,6.7,2.2]])
print(result3)

[0]
[1]
[2]


## **Home Work:** 
* Reading Exercise1: [Refer more from sklearn doc](https://scikit-learn.org/stable/modules/neighbors.html)

* Reading Exercise 2: https://www.kaggle.com/dkim1992/grid-search-vs-random-search

* Once you complete above reading answer below Questions?

    1. In KNN argument **algorithm**, will not accept below value?

        <input type="radio" disabled> brute

        <input type="radio" disabled> KDtree

        <input type="radio" disabled> balltree

        <input type="radio" disabled checked> random tree

    2. KNN is ?

        <input type="radio" disabled checked> non-parametric method

        <input type="radio" disabled> parametric method

        [Refer about Nonparametric statistics](https://en.wikipedia.org/wiki/Nonparametric_statistics#Applications_and_purpose)

        [Refer about Parametric statistics](https://en.wikipedia.org/wiki/Parametric_statistics)
        
        
    3. What is estimator ?
    2. When to go for brute, kd tree and ball tree?
    3. In KNN weights parameter has two values uniform and distance. What is the difference?
    4. p=1 then what type of distance?
    5. p=2 then what type of distance?
