# Get data

In [49]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
df =pd.read_csv("C:/Users/ramreddymyla/Google Drive/01 DS ML DL NLP and AI With Python Lab Copy/02 Lab Data/Python/iris.csv")

In [50]:
X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].values
type(X)

numpy.ndarray

In [51]:
y=df.species.replace(to_replace=['setosa', 'versicolor', 'virginica'],value=[0,1,2]).values
type(y)


numpy.ndarray

# split(train (70%),test(30%))

In [52]:
def fun_square_and_cube(arg1):
    return arg1 **2 ,arg1 **3

In [53]:
c,s = fun_square_and_cube(2)

In [54]:
s

8

In [55]:
c

4

In [56]:
X_train,X_test,y_train,y_test=train_test_split(X,y,
                                               test_size =0.3,
                                               random_state=32,
                                               shuffle =True,
                                               stratify=y)

In [57]:
import numpy as np
np.unique(y,return_counts=True)

(array([0, 1, 2], dtype=int64), array([50, 50, 50], dtype=int64))

In [58]:
np.unique(y_train,return_counts=True)

(array([0, 1, 2], dtype=int64), array([35, 35, 35], dtype=int64))

In [59]:
np.unique(y_test,return_counts=True)

(array([0, 1, 2], dtype=int64), array([15, 15, 15], dtype=int64))

# fit the model
* training the model

In [60]:
model=KNeighborsClassifier()

In [61]:
model.fit(X_train,y_train) # 105 samples

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [62]:
model.n_neighbors

5

# predict

In [63]:
model.predict_proba(X_test)

array([[0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0.6, 0.4],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [0. , 0.4, 0.6],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [0. , 0.8, 0.2],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0. 

In [64]:
y_test_pred=model.predict(X_test)

In [65]:
y_test_pred

array([1, 0, 0, 0, 0, 1, 1, 0, 2, 2, 1, 0, 1, 1, 2, 0, 2, 2, 1, 2, 0, 0,
       0, 2, 2, 0, 2, 0, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 0, 2, 0, 0,
       2], dtype=int64)

In [66]:
X_test

array([[5. , 2.3, 3.3, 1. ],
       [5. , 3.5, 1.6, 0.6],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3. , 1.6, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [6.1, 3. , 4.6, 1.4],
       [6.5, 2.8, 4.6, 1.5],
       [4.9, 3.1, 1.5, 0.1],
       [7.7, 2.6, 6.9, 2.3],
       [6.5, 3. , 5.2, 2. ],
       [5.9, 3. , 4.2, 1.5],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 3. , 4.5, 1.5],
       [6.2, 2.2, 4.5, 1.5],
       [7.9, 3.8, 6.4, 2. ],
       [5. , 3.6, 1.4, 0.2],
       [5.9, 3.2, 4.8, 1.8],
       [7.1, 3. , 5.9, 2.1],
       [6.2, 2.9, 4.3, 1.3],
       [7.7, 3.8, 6.7, 2.2],
       [5. , 3.4, 1.5, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [6.4, 3.1, 5.5, 1.8],
       [7.3, 2.9, 6.3, 1.8],
       [5.4, 3.9, 1.7, 0.4],
       [6.4, 2.8, 5.6, 2.2],
       [5.1, 3.8, 1.5, 0.3],
       [7.4, 2.8, 6.1, 1.9],
       [5.4, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 2.6, 3.5, 1. ],
       [6.3, 3.3, 6. , 2.5],
       [7.7, 3

In [67]:
y_test

array([1, 0, 0, 0, 0, 1, 1, 0, 2, 2, 1, 0, 1, 1, 2, 0, 1, 2, 1, 2, 0, 0,
       0, 2, 2, 0, 2, 0, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 0, 2, 0, 0,
       2], dtype=int64)

In [68]:
y_test_pred

array([1, 0, 0, 0, 0, 1, 1, 0, 2, 2, 1, 0, 1, 1, 2, 0, 2, 2, 1, 2, 0, 0,
       0, 2, 2, 0, 2, 0, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 0, 2, 0, 0,
       2], dtype=int64)

In [69]:
sum(y_test == y_test_pred)

44

In [70]:
len(y_test)

45

In [71]:
44/45

0.9777777777777777

# accuracy

In [72]:
from sklearn.metrics import accuracy_score

In [73]:
accuracy_score(y_test,y_test_pred)

0.9777777777777777

# hyper parameter tunning

## our own code

In [74]:
KNeighborsClassifier?

Init signature:
KNeighborsClassifier(
    n_neighbors=5,
    weights='uniform',
    algorithm='auto',
    leaf_size=30,
    p=2,
    metric='minkowski',
    metric_params=None,
    n_jobs=None,
    **kwargs,
)
Docstring:     
Classifier implementing the k-nearest neighbors vote.

Read more in the :ref:`User Guide <classification>`.

Parameters
----------
n_neighbors : int, optional (default = 5)
    Number of neighbors to use by default for :meth:`kneighbors` queries.

weights : str or callable, optional (default = 'uniform')
    weight function used in prediction.  Possible values:

    - 'uniform' : uniform weights.  All points in each neighborhood
      are weighted equally.
    - 'distance' : weight points by the inverse of their distance.
      in this case, closer neighbors of a query point will have a
      greater influence than neighbors which are further away.
    - [callable] : a user-defined function which accepts an
      array of distances, and returns an array of the sam

In [75]:
model

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [76]:
acc=[]
for i in range(2,21):
    for alg in  ['ball_tree', 'kd_tree', 'brute']:
        for p in [1,2]:
            for w in ["uniform","distance"]:
                model=KNeighborsClassifier(n_neighbors=i,algorithm=alg,p=p,weights=w)
                model.fit(X_train,y_train) # 105 samples
                y_test_pred=model.predict(X_test)
                acc.append((i,alg,p,w,accuracy_score(y_test,y_test_pred)))
acc   

[(2, 'ball_tree', 1, 'uniform', 0.9777777777777777),
 (2, 'ball_tree', 1, 'distance', 0.9777777777777777),
 (2, 'ball_tree', 2, 'uniform', 0.9777777777777777),
 (2, 'ball_tree', 2, 'distance', 0.9777777777777777),
 (2, 'kd_tree', 1, 'uniform', 0.9777777777777777),
 (2, 'kd_tree', 1, 'distance', 0.9777777777777777),
 (2, 'kd_tree', 2, 'uniform', 0.9777777777777777),
 (2, 'kd_tree', 2, 'distance', 0.9777777777777777),
 (2, 'brute', 1, 'uniform', 0.9777777777777777),
 (2, 'brute', 1, 'distance', 0.9777777777777777),
 (2, 'brute', 2, 'uniform', 0.9777777777777777),
 (2, 'brute', 2, 'distance', 0.9777777777777777),
 (3, 'ball_tree', 1, 'uniform', 0.9777777777777777),
 (3, 'ball_tree', 1, 'distance', 0.9777777777777777),
 (3, 'ball_tree', 2, 'uniform', 0.9777777777777777),
 (3, 'ball_tree', 2, 'distance', 0.9777777777777777),
 (3, 'kd_tree', 1, 'uniform', 0.9777777777777777),
 (3, 'kd_tree', 1, 'distance', 0.9777777777777777),
 (3, 'kd_tree', 2, 'uniform', 0.9777777777777777),
 (3, 'kd_tree'

In [77]:
KNeighborsClassifier?

Init signature:
KNeighborsClassifier(
    n_neighbors=5,
    weights='uniform',
    algorithm='auto',
    leaf_size=30,
    p=2,
    metric='minkowski',
    metric_params=None,
    n_jobs=None,
    **kwargs,
)
Docstring:     
Classifier implementing the k-nearest neighbors vote.

Read more in the :ref:`User Guide <classification>`.

Parameters
----------
n_neighbors : int, optional (default = 5)
    Number of neighbors to use by default for :meth:`kneighbors` queries.

weights : str or callable, optional (default = 'uniform')
    weight function used in prediction.  Possible values:

    - 'uniform' : uniform weights.  All points in each neighborhood
      are weighted equally.
    - 'distance' : weight points by the inverse of their distance.
      in this case, closer neighbors of a query point will have a
      greater influence than neighbors which are further away.
    - [callable] : a user-defined function which accepts an
      array of distances, and returns an array of the sam

In [78]:
from sklearn.model_selection import GridSearchCV

In [79]:
GridSearchCV?

Init signature:
GridSearchCV(
    estimator,
    param_grid,
    scoring=None,
    n_jobs=None,
    iid='warn',
    refit=True,
    cv='warn',
    verbose=0,
    pre_dispatch='2*n_jobs',
    error_score='raise-deprecating',
    return_train_score=False,
)
Docstring:     
Exhaustive search over specified parameter values for an estimator.

Important members are fit, predict.

GridSearchCV implements a "fit" and a "score" method.
It also implements "predict", "predict_proba", "decision_function",
"transform" and "inverse_transform" if they are implemented in the
estimator used.

The parameters of the estimator used to apply these methods are optimized
by cross-validated grid-search over a parameter grid.

Read more in the :ref:`User Guide <grid_search>`.

Parameters
----------
estimator : estimator object.
    This is assumed to implement the scikit-learn estimator interface.
    Either estimator needs to provide a ``score`` function,
    or ``scoring`` must be passed.

param_grid : dict