In [1]:
import pandas as pd
df = pd.read_csv("auto-mpg.csv")
df.head()

mpg  displ   hp  weight  accel  size
0  18.0  250.0   88    3139   14.5  15.0
1   9.0  304.0  193    4732   18.5  20.0
2  36.1   91.0   60    1800   16.4  10.0
3  18.5  250.0   98    3525   19.0  15.0
4  34.3   97.0   78    2188   15.8  10.0

In [2]:
X,y=df.iloc[:,1:].values,df.iloc[:,0].values

In [3]:
X[:5]

array([[ 250. ,   88. , 3139. ,   14.5,   15. ],
       [ 304. ,  193. , 4732. ,   18.5,   20. ],
       [  91. ,   60. , 1800. ,   16.4,   10. ],
       [ 250. ,   98. , 3525. ,   19. ,   15. ],
       [  97. ,   78. , 2188. ,   15.8,   10. ]])

In [4]:
y[:5]

array([18. ,  9. , 36.1, 18.5, 34.3])

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)

In [7]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor(n_estimators=300)
rf.fit(X_train,y_train)


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=300,
                      n_jobs=None, oob_score=False, random_state=None,
                      verbose=0, warm_start=False)

In [8]:
y_test_pred=rf.predict(X_test)

In [9]:
from sklearn.metrics import mean_squared_error
import numpy as np
error=np.sqrt(mean_squared_error(y_test,y_test_pred))

In [10]:
error

4.087267994043438

In [11]:
rf.feature_importances_

array([0.39370021, 0.17763849, 0.17813139, 0.06674084, 0.18378907])

In [12]:
df.head()

mpg  displ   hp  weight  accel  size
0  18.0  250.0   88    3139   14.5  15.0
1   9.0  304.0  193    4732   18.5  20.0
2  36.1   91.0   60    1800   16.4  10.0
3  18.5  250.0   98    3525   19.0  15.0
4  34.3   97.0   78    2188   15.8  10.0