# Get data(Files,RDBMS,NO-SQL DATABASES,GRAPH Databases)

In [1]:
import pandas as pd
df =pd.read_csv("iris.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal_length    150 non-null float64
sepal_width     150 non-null float64
petal_length    150 non-null float64
petal_width     150 non-null float64
species         150 non-null object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [2]:
# desc stats
df.describe(include="all")

sepal_length  sepal_width  petal_length  petal_width    species
count     150.000000   150.000000    150.000000   150.000000        150
unique           NaN          NaN           NaN          NaN          3
top              NaN          NaN           NaN          NaN  virginica
freq             NaN          NaN           NaN          NaN         50
mean        5.843333     3.054000      3.758667     1.198667        NaN
std         0.828066     0.433594      1.764420     0.763161        NaN
min         4.300000     2.000000      1.000000     0.100000        NaN
25%         5.100000     2.800000      1.600000     0.300000        NaN
50%         5.800000     3.000000      4.350000     1.300000        NaN
75%         6.400000     3.300000      5.100000     1.800000        NaN
max         7.900000     4.400000      6.900000     2.500000        NaN

In [3]:
df.species.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [4]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
df.iloc[[1,50,100]]

sepal_length  sepal_width  petal_length  petal_width     species
1             4.9          3.0           1.4          0.2      setosa
50            7.0          3.2           4.7          1.4  versicolor
100           6.3          3.3           6.0          2.5   virginica

# Pre processing of data
- we will learn more next chapters

# Identify X(Independent Variables),y(Dependent Varaibale)
- **Business Problem Statement :** For a given sepal_length	sepal_width	petal_length	petal_width what is the type of flower/species?

In [6]:
X,y=df.iloc[:,:-1],df.iloc[:,-1]

In [7]:
#X,y=df.drop(["species"],axis=1),df.drop(["sepal_length","sepal_width","petal_length","petal_width"],axis=1)

In [8]:
X.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [9]:
y.head()

0    setosa
1    setosa
2    setosa
3    setosa
4    setosa
Name: species, dtype: object

In [10]:
y=y.replace(['setosa', 'versicolor', 'virginica'],[0,1,2])

In [11]:
X=X.values # convert df into 2d np array
y=y.values # seriex into 1d np array

In [12]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [13]:
y[:5]

array([0, 0, 0, 0, 0], dtype=int64)

# Split the data into Train and Test

In [14]:
from sklearn.model_selection import train_test_split
a=train_test_split(X,y,
                test_size =0.3,
                random_state = 1)

In [15]:
type(a)

list

In [16]:
len(a)

4

In [17]:
a

[array([[7.7, 2.6, 6.9, 2.3],
        [5.7, 3.8, 1.7, 0.3],
        [5. , 3.6, 1.4, 0.2],
        [4.8, 3. , 1.4, 0.3],
        [5.2, 2.7, 3.9, 1.4],
        [5.1, 3.4, 1.5, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [7.7, 3.8, 6.7, 2.2],
        [6.9, 3.1, 5.4, 2.1],
        [7.3, 2.9, 6.3, 1.8],
        [6.4, 2.8, 5.6, 2.2],
        [6.2, 2.8, 4.8, 1.8],
        [6. , 3.4, 4.5, 1.6],
        [7.7, 2.8, 6.7, 2. ],
        [5.7, 3. , 4.2, 1.2],
        [4.8, 3.4, 1.6, 0.2],
        [5.7, 2.5, 5. , 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [4.8, 3. , 1.4, 0.1],
        [4.7, 3.2, 1.3, 0.2],
        [6.5, 3. , 5.8, 2.2],
        [4.6, 3.4, 1.4, 0.3],
        [6.1, 3. , 4.9, 1.8],
        [6.5, 3.2, 5.1, 2. ],
        [6.7, 3.1, 4.4, 1.4],
        [5.7, 2.8, 4.5, 1.3],
        [6.7, 3.3, 5.7, 2.5],
        [6. , 3. , 4.8, 1.8],
        [5.1, 3.8, 1.6, 0.2],
        [6. , 2.2, 4. , 1. ],
        [6.4, 2.9, 4.3, 1.3],
        [6.5, 3. , 5.5, 1.8],
        [5. , 2.3, 3.3, 1. ],
        [6

In [18]:
X_train,X_test,y_train,y_test=train_test_split(X,y,
                test_size =0.3,
                random_state = 1,
                                              stratify=y)

In [19]:
len(X_train) # 70%

105

In [20]:
len(X_test) #30%

45

In [21]:
len(y_train)

105

In [22]:
len(y_test)

45

In [23]:
# stratify
import numpy as np
np.unique(y,return_counts=True) # orginal Data ratio is 50:50:50 = 1:1:1

(array([0, 1, 2], dtype=int64), array([50, 50, 50], dtype=int64))

In [24]:
np.unique(y_train,return_counts=True) ## train Data ratio is 1:1:1

(array([0, 1, 2], dtype=int64), array([35, 35, 35], dtype=int64))

In [25]:
np.unique(y_test,return_counts=True) ## train Data ratio is 1:1:1

(array([0, 1, 2], dtype=int64), array([15, 15, 15], dtype=int64))

# Fit / Train model using train data

In [26]:
from sklearn.neighbors import KNeighborsClassifier # class
model=KNeighborsClassifier(n_neighbors=5) # object of the class

In [27]:
model

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [28]:
model.fit(X_train,y_train) # method

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

# Predict on test data

In [31]:
X_test.shape

(45, 4)

In [32]:
model.predict_proba(X_test)
# setosa(0) # versicolor(1) # verginica(2)

array([[0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [0. , 0.6, 0.4],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0.4, 0.6],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0.8, 0.2],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0.2, 0.8],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [0. , 0.2, 0.8],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [0. , 0.4

In [33]:
model.predict(X_test)
# setosa(0) # versicolor(1) # verginica(2)

array([2, 0, 0, 1, 1, 1, 2, 1, 2, 0, 0, 2, 0, 1, 0, 1, 2, 1, 1, 2, 2, 0,
       1, 2, 1, 1, 1, 2, 0, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 2, 2, 1, 0,
       0], dtype=int64)

In [36]:
y_test_pred=model.predict(X_test)
# machine estimated/Predicated 
y_test_pred

array([2, 0, 0, 1, 1, 1, 2, 1, 2, 0, 0, 2, 0, 1, 0, 1, 2, 1, 1, 2, 2, 0,
       1, 2, 1, 1, 1, 2, 0, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 2, 2, 1, 0,
       0], dtype=int64)

In [35]:
# ground truth data
y_test

array([2, 0, 0, 2, 1, 1, 2, 1, 2, 0, 0, 2, 0, 1, 0, 1, 2, 1, 1, 2, 2, 0,
       1, 2, 1, 1, 1, 2, 0, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 2, 2, 1, 0,
       0], dtype=int64)

In [39]:
sum(y_test == y_test_pred)/len(y_test) # correctly identified / total no of samples

0.9777777777777777

# Metrics(Accuracy)

In [41]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_test_pred) # unseen data score

0.9777777777777777

In [43]:
accuracy_score(y_train,model.predict(X_train)) # seen data score

0.9809523809523809

In [44]:
# most of the cases 
# training data score > test data score
# we always need to belive test data score 

# underfit
    # Score will be less on train and test data
# Overfit
    # on Training data more score but on testing data less score


# hyper parameter tunning

In [67]:
scores = []
for i in range(1,20):
    for w in ["uniform","distance"]:
        for p in [1,2]:
            for alg in ['ball_tree', 'kd_tree', 'brute']:
                model=KNeighborsClassifier(n_neighbors=i,weights=w,p=p,algorithm=alg)
                model.fit(X_train,y_train)
                y_test_pred=model.predict(X_test)
                scores.append((i,w,p,alg,accuracy_score(y_test,y_test_pred)))
#scores   

In [68]:
from sklearn.model_selection import GridSearchCV
GridSearchCV?

Init signature:
GridSearchCV(
    estimator,
    param_grid,
    scoring=None,
    n_jobs=None,
    iid='warn',
    refit=True,
    cv='warn',
    verbose=0,
    pre_dispatch='2*n_jobs',
    error_score='raise-deprecating',
    return_train_score=False,
)
Docstring:     
Exhaustive search over specified parameter values for an estimator.

Important members are fit, predict.

GridSearchCV implements a "fit" and a "score" method.
It also implements "predict", "predict_proba", "decision_function",
"transform" and "inverse_transform" if they are implemented in the
estimator used.

The parameters of the estimator used to apply these methods are optimized
by cross-validated grid-search over a parameter grid.

Read more in the :ref:`User Guide <grid_search>`.

Parameters
----------
estimator : estimator object.
    This is assumed to implement the scikit-learn estimator interface.
    Either estimator needs to provide a ``score`` function,
    or ``scoring`` must be passed.

param_grid : dict